site_name: Unofficial Discord API docs

theme:
  name: material

  palette:
    scheme: slate

  features:
    - content.code.copy

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
